### PR TITLE
composer.json: add support for drush 12.x

### PR DESCRIPTION
**Pull request by elgandoz**

### CODE REVIEW

**Comment by mortenson** [comment]
@elgandoz Someone on Drupal.org mentioned that Tome doesn't work at all with Drush 12 - have you had good luck with using it after applying a patch like this?

**Comment by elgandoz** [comment]
Sorry @mortenson I was too fast with this. Yes you're very right, but I'm working on it.

**Comment by jeremypeter** [comment]
Added a comment to https://www.drupal.org/project/tome/issues/3375608#comment-15177060

**Comment by webdevhu** [comment]
Was the code in c02885de989a37912bf7548b56a560687ceb4ded manually added to the composer.json file or was a command run to automatically add it? If it was manually added, I was curious as to where it should go in the file.

**Comment by jeremypeter** [comment]
@webdevhu Added comment here https://www.drupal.org/project/tome/issues/3375608#comment-15259544

**Pull request merged**
